create sequence SEQ_MEMBER_NO start with 1 increment by 1 maxvalue 99999999;
create sequence SEQ_GALLERY_NO start with 1 increment by 1 maxvalue 99999999;
create sequence SEQ_SHARING_NO start with 1 increment by 1 maxvalue 99999999;
create sequence SEQ_FREE_NO start with 1 increment by 1 maxvalue 99999999;
create sequence SEQ_NOTICE_NO start with 1 increment by 1 maxvalue 99999999;
create sequence SEQ_VERSES_NO start with 1 increment by 1 maxvalue 99999999;
create sequence SEQ_COLUMN_NO start with 1 increment by 1 maxvalue 99999999;
create sequence SEQ_REFERENCE_NO start with 1 increment by 1 maxvalue 99999999;
create sequence SEQ_NATION_NO start with 1 increment by 1 maxvalue 99999999;
create sequence SEQ_FAMILY_NO start with 1 increment by 1 maxvalue 99999999;
create sequence SEQ_INTRO_NO start with 1 increment by 1 maxvalue 99999999;

-- 테이블 생성
DROP TABLE IF EXISTS `MEMBER`;

CREATE TABLE `MEMBER` (
	`MEMBER_NO`	bigint	PRIMARY KEY AUTO_INCREMENT not null	COMMENT 'SEQ_MEMBER_NO',
	`MEMBER_NAME`	VARCHAR(20)	NOT NULL,
	`MEMBER_PW`	VARCHAR(20)	NOT NULL,
	`MEMBER_RANK`	VARCHAR(5)	NOT NULL	DEFAULT 'N'	COMMENT 'A: 어드민, F : 가족, N : 손님',
	`MEMBER_EMAIL`	VARCHAR(20)	NULL,
	`MEMBER_DEL_FL`	VARCHAR(2)	NULL	DEFAULT 'N'	COMMENT 'N(회원) Y(탈퇴한 회원)',
	`Field`	VARCHAR(255)	NULL
);

DROP TABLE IF EXISTS `FREE`;

CREATE TABLE `FREE` (
	`FREE_NO`	bigint	PRIMARY KEY AUTO_INCREMENT not null	COMMENT 'SEQ_FREE_NO',
	`MEMBER_NO`	bigint	NOT NULL,
	`FREE_TITLE`	VARCHAR(20)	NOT NULL,
	`FREE_CONTENT`	VARCHAR(100)	NOT NULL,
	`FREE_DELETE_FL`	VARCHAR(2)	NOT NULL	DEFAULT 'N'	COMMENT '(Y) 삭제됨, (N) 삭제안됨',
	`FREE_DATE`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS `SHARING`;

CREATE TABLE `SHARING` (
	`SHARING_NO`	bigint	PRIMARY KEY AUTO_INCREMENT not null	COMMENT 'SEQ_SHARING_NO',
	`MEMBER_NO`	bigint	NOT NULL,
	`SHARING_TITLE`	VARCHAR(20)	NOT NULL,
	`SHARING_CONTENT`	VARCHAR(100)	NOT NULL,
	`SHARING_DELETE_FL`	VARCHAR(2)	NOT NULL	DEFAULT 'N'	COMMENT '(Y) 삭제됨, (N) 삭제안됨',
	`SHARING_DATE`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS `NOTICE`;

CREATE TABLE `NOTICE` (
	`NOTICE_NO`	bigint	PRIMARY KEY AUTO_INCREMENT not null	COMMENT 'SEQ_NOTICE_NO',
	`MEMBER_NO`	bigint	NOT NULL,
	`NOTICE_TITLE`	VARCHAR(20)	NOT NULL,
	`NOTICE_CONTENT`	VARCHAR(100)	NOT NULL,
	`NOTICE_DELETE_FL`	VARCHAR(2)	NOT NULL	DEFAULT 'N'	COMMENT '(Y) 삭제됨, (N) 삭제안됨',
	`NOTICE_DATE`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS `CopyOfnotice`;

CREATE TABLE `CopyOfnotice` (
	`BEST_NOTICE_NO`	bigint	NOT NULL,
	`NOTICE_NO`	bigint	NOT NULL
);

DROP TABLE IF EXISTS `VERSES`;

CREATE TABLE `VERSES` (
	`VERSES_NO`	bigint	PRIMARY KEY AUTO_INCREMENT not null	COMMENT 'SEQ_VERSES_NO',
	`MEMBER_NO`	bigint	NOT NULL,
	`VERSES_TITLE`	VARCHAR(20)	NOT NULL,
	`VERSES_CONTENT`	VARCHAR(100)	NOT NULL,
	`VERSES_DELETE_FL`	VARCHAR(2)	NOT NULL	DEFAULT 'N'	COMMENT '(Y) 삭제됨, (N) 삭제안됨',
	`VERSES_DATE`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS `COLUMN`;

CREATE TABLE `COLUMN` (
	`COLUMN_NO`	bigint	PRIMARY KEY AUTO_INCREMENT not null	COMMENT 'SEQ_COLUMN_NO',
	`MEMBER_NO`	bigint	NOT NULL,
	`COLUMN_TITLE`	VARCHAR(20)	NOT NULL,
	`COLUMN_CONTENT`	VARCHAR(100)	NOT NULL,
	`COLUMN_DELETE_FL`	VARCHAR(2)	NOT NULL	DEFAULT 'N'	COMMENT '(Y) 삭제됨, (N) 삭제안됨',
	`COLUMN_DATE`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS `REFERENCE`;

CREATE TABLE `REFERENCE` (
	`REFERENCE_NO`	bigint	PRIMARY KEY AUTO_INCREMENT not null	COMMENT 'SEQ_REFERENCE_NO',
	`MEMBER_NO`	bigint	NOT NULL,
	`REFERENCE_TITLE`	VARCHAR(20)	NOT NULL,
	`REFERENCE_CONTENT`	VARCHAR(100)	NOT NULL,
	`REFERENCE_DELETE_FL`	VARCHAR(2)	NOT NULL	DEFAULT 'N'	COMMENT '(Y) 삭제됨, (N) 삭제안됨',
	`REFERENCE_DATE`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS `NATIONS`;

CREATE TABLE `NATIONS` (
	`NATIONS_NO`	bigint	PRIMARY KEY AUTO_INCREMENT not null	COMMENT 'SEQ_NATION_NO',
	`MEMBER_NO`	bigint	NOT NULL,
	`NATIONS_TITLE`	VARCHAR(20)	NOT NULL,
	`NATIONS_CONTENT`	VARCHAR(100)	NOT NULL,
	`NATIONS_DELETE_FL`	VARCHAR(2)	NOT NULL	DEFAULT 'N'	COMMENT '(Y) 삭제됨, (N) 삭제안됨',
	`NATIONS_DATE`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS `FAMILY`;

CREATE TABLE `FAMILY` (
	`FAMILY_NO`	bigint	PRIMARY KEY AUTO_INCREMENT not null	COMMENT 'SEQ_FAMILY_NO',
	`MEMBER_NO`	bigint	NOT NULL,
	`FAMILY_TITLE`	VARCHAR(20)	NOT NULL,
	`FAMILY_CONTENT`	VARCHAR(100)	NOT NULL,
	`FAMILY_DELETE_FL`	VARCHAR(2)	NOT NULL	DEFAULT 'N'	COMMENT '(Y) 삭제됨, (N) 삭제안됨',
	`FAMILY_DATE`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS `GALLERY`;

CREATE TABLE `GALLERY` (
	`GALLERY_NO`	bigint	PRIMARY KEY AUTO_INCREMENT not null	COMMENT 'SEQ_GALLERY_NO',
	`MEMBER_NO`	bigint	NOT NULL,
	`GALLERY_CONTENT`	VARCHAR(100)	NOT NULL,
	`FAMILY_DELETE_FL`	VARCHAR(2)	NOT NULL	DEFAULT 'N'	COMMENT '(Y) 삭제됨, (N) 삭제안됨',
	`FAMILY_DATE`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`GALLERY_CATEGORY`	VARCHAR(2)	NOT NULL	COMMENT '1 (나사로의집풍경), 2(거금도풍경), 3(농특산물소개)',
	`Field`	VARCHAR(255)	NULL
);

DROP TABLE IF EXISTS `INTRO`;

CREATE TABLE `INTRO` (
	`INTRO_NO`	bigint	PRIMARY KEY AUTO_INCREMENT not null	COMMENT 'SEQ_INTRO_NO',
	`MEMBER_NO`	bigint	NOT NULL,
	`INTRO_CONTENT`	VARCHAR(100)	NULL
);

ALTER TABLE `MEMBER` ADD CONSTRAINT `PK_MEMBER` PRIMARY KEY (
	`MEMBER_NO`
);

ALTER TABLE `FREE` ADD CONSTRAINT `PK_FREE` PRIMARY KEY (
	`FREE_NO`,
	`MEMBER_NO`
);

ALTER TABLE `SHARING` ADD CONSTRAINT `PK_SHARING` PRIMARY KEY (
	`SHARING_NO`,
	`MEMBER_NO`
);

ALTER TABLE `NOTICE` ADD CONSTRAINT `PK_NOTICE` PRIMARY KEY (
	`NOTICE_NO`,
	`MEMBER_NO`
);

ALTER TABLE `CopyOfnotice` ADD CONSTRAINT `PK_COPYOFNOTICE` PRIMARY KEY (
	`BEST_NOTICE_NO`,
	`NOTICE_NO`
);

ALTER TABLE `VERSES` ADD CONSTRAINT `PK_VERSES` PRIMARY KEY (
	`VERSES_NO`,
	`MEMBER_NO`
);

ALTER TABLE `COLUMN` ADD CONSTRAINT `PK_COLUMN` PRIMARY KEY (
	`COLUMN_NO`,
	`MEMBER_NO`
);

ALTER TABLE `REFERENCE` ADD CONSTRAINT `PK_REFERENCE` PRIMARY KEY (
	`REFERENCE_NO`,
	`MEMBER_NO`
);

ALTER TABLE `NATIONS` ADD CONSTRAINT `PK_NATIONS` PRIMARY KEY (
	`NATIONS_NO`,
	`MEMBER_NO`
);

ALTER TABLE `FAMILY` ADD CONSTRAINT `PK_FAMILY` PRIMARY KEY (
	`FAMILY_NO`,
	`MEMBER_NO`
);

ALTER TABLE `GALLERY` ADD CONSTRAINT `PK_GALLERY` PRIMARY KEY (
	`GALLERY_NO`,
	`MEMBER_NO`
);

ALTER TABLE `INTRO` ADD CONSTRAINT `PK_INTRO` PRIMARY KEY (
	`INTRO_NO`,
	`MEMBER_NO`
);

ALTER TABLE `FREE` ADD CONSTRAINT `FK_MEMBER_TO_FREE_1` FOREIGN KEY (
	`MEMBER_NO`
)
REFERENCES `MEMBER` (
	`MEMBER_NO`
);

ALTER TABLE `SHARING` ADD CONSTRAINT `FK_MEMBER_TO_SHARING_1` FOREIGN KEY (
	`MEMBER_NO`
)
REFERENCES `MEMBER` (
	`MEMBER_NO`
);

ALTER TABLE `NOTICE` ADD CONSTRAINT `FK_MEMBER_TO_NOTICE_1` FOREIGN KEY (
	`MEMBER_NO`
)
REFERENCES `MEMBER` (
	`MEMBER_NO`
);

ALTER TABLE `CopyOfnotice` ADD CONSTRAINT `FK_NOTICE_TO_CopyOfnotice_1` FOREIGN KEY (
	`NOTICE_NO`
)
REFERENCES `NOTICE` (
	`NOTICE_NO`
);

ALTER TABLE `VERSES` ADD CONSTRAINT `FK_MEMBER_TO_VERSES_1` FOREIGN KEY (
	`MEMBER_NO`
)
REFERENCES `MEMBER` (
	`MEMBER_NO`
);

ALTER TABLE `COLUMN` ADD CONSTRAINT `FK_MEMBER_TO_COLUMN_1` FOREIGN KEY (
	`MEMBER_NO`
)
REFERENCES `MEMBER` (
	`MEMBER_NO`
);

ALTER TABLE `REFERENCE` ADD CONSTRAINT `FK_MEMBER_TO_REFERENCE_1` FOREIGN KEY (
	`MEMBER_NO`
)
REFERENCES `MEMBER` (
	`MEMBER_NO`
);

ALTER TABLE `NATIONS` ADD CONSTRAINT `FK_MEMBER_TO_NATIONS_1` FOREIGN KEY (
	`MEMBER_NO`
)
REFERENCES `MEMBER` (
	`MEMBER_NO`
);

ALTER TABLE `FAMILY` ADD CONSTRAINT `FK_MEMBER_TO_FAMILY_1` FOREIGN KEY (
	`MEMBER_NO`
)
REFERENCES `MEMBER` (
	`MEMBER_NO`
);

ALTER TABLE `GALLERY` ADD CONSTRAINT `FK_MEMBER_TO_GALLERY_1` FOREIGN KEY (
	`MEMBER_NO`
)
REFERENCES `MEMBER` (
	`MEMBER_NO`
);

ALTER TABLE `INTRO` ADD CONSTRAINT `FK_MEMBER_TO_INTRO_1` FOREIGN KEY (
	`MEMBER_NO`
)
REFERENCES `MEMBER` (
	`MEMBER_NO`
);

insert  into `MEMBER`  value (default, 'gaya123', '강가야', '123', 'A', '', default);
insert  into `NATIONS`  value (default, 1, '열방을 위한 기도1', '내용입니다', 'N', default);
select * from `COLUMN` c  ;
select * from `MEMBER` m  ;
select * from `MEMBER` m  ;
select * from `NOTICE` m  ;
select * from GALLERY g JOIN GALLERYIMG gi on g.GALLERY_NO = gi.GALLERY_NO JOIN MEMBER m on g.member_no=m.member_no;
SELECT * FROM `FREE` WHERE free_no = 1;
insert  into `GALLERY`  value (default, #{memberId}, #{galleryContent}, default, default, #{galleryCategory});
insert  into `GALLERYIMG`  value (default, #{GalleryNo}, #{galleryPath}, #{galleryOrder});

select * from `GALLERYIMG` g ;
select * from `GALLERYIMG` g ;

        SELECT g.gallery_NO, 
			m.MEMBER_NAME, 
			g.gallery_CONTENT, 
			g.gallery_category, 
			DATE_FORMAT(g.gallery_DATE, '%m-%d') gallery_DATE 
        FROM GALLERY g 
        JOIN MEMBER m on g.member_no=m.member_no
        WHERE gallery_delete_fl='N' 
        AND gallery_category=1
        ORDER BY gallery_NO DESC;